definitions:
  request.Base64Request:
    properties:
      base64:
        type: string
      hocrMode:
        type: boolean
      languages:
        description: 检测语言 eng chi_sim等
        type: string
      preserveInterwordSpaces:
        type: boolean
      specialHandling:
        description: '特殊处理的保留字段: 0.无 | 1.常规通气'
        type: integer
      trimLineFeed:
        type: boolean
      whitelist:
        type: string
    required:
    - base64
    type: object
  request.Base64WithPixelPointRequest:
    properties:
      base64:
        type: string
      hocrMode:
        type: boolean
      languages:
        description: 检测语言 eng chi_sim等
        type: string
      matrixPixels:
        items:
          $ref: '#/definitions/request.MatrixPixel'
        type: array
      preserveInterwordSpaces:
        type: boolean
      specialHandling:
        description: '特殊处理的保留字段: 0.无 | 1.常规通气'
        type: integer
      trimLineFeed:
        type: boolean
      whitelist:
        type: string
    required:
    - base64
    - matrixPixels
    type: object
  request.MatrixPixel:
    properties:
      pointA:
        $ref: '#/definitions/request.Pixel'
      pointB:
        $ref: '#/definitions/request.Pixel'
    type: object
  request.Pixel:
    properties:
      x:
        type: integer
      "y":
        type: integer
    type: object
  response.HttpResponse:
    properties:
      data:
        type: object
      message:
        type: object
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/ocr/base64:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: file
        required: true
        schema:
          $ref: '#/definitions/request.Base64Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: OCR识别BASE64格式的图片
      tags:
      - ocr
  /api/ocr/file:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 图片文件
        in: formData
        name: file
        required: true
        type: file
      - description: '可选项: 指定要识别的语言种类，如eng(英文) chi_sim(简体中文)，可以用逗号隔开指定多个, 不指定默认是eng'
        in: formData
        name: languages
        type: string
      - description: '可选项: 为空检测全部字符。如果填写，仅会检测白名单之内的字符'
        in: formData
        name: whitelist
        type: string
      - description: '可选项: 是否开始HOCR，一般默认为false'
        in: formData
        name: hocrMode
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: OCR识别上传的整张图片
      tags:
      - ocr
  /api/ocr/scan-crop-base64:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: file
        required: true
        schema:
          $ref: '#/definitions/request.Base64WithPixelPointRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: OCR识别剪切后的BASE64格式的图片
      tags:
      - ocr
  /api/ocr/scan-crop-file:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 图片文件
        in: formData
        name: file
        required: true
        type: file
      - description: '裁剪像素点。必须是下面格式的合法json字符串： [{ pointA: {x: 127, y: 249}, pointB: {x: 983, y: 309}}]'
        in: formData
        name: matrixPixels
        required: true
        type: string
      - description: '可选项: 指定要识别的语言种类，如eng(英文) chi_sim(简体中文)，可以用逗号隔开指定多个, 不指定默认是eng'
        in: formData
        name: languages
        type: string
      - description: '可选项: 为空检测全部字符。如果填写，仅会检测白名单之内的字符'
        in: formData
        name: whitelist
        type: string
      - description: '可选项: 是否开始HOCR，一般默认为false'
        in: formData
        name: hocrMode
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: OCR识别像素点裁剪之后的图片文字
      tags:
      - ocr
swagger: "2.0"
